apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcc-logs
  labels:
    app: pcc-logs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pcc-logs
  template:
    metadata:
      labels:
        app: pcc-logs
    spec:
      containers:
        - name: pcc-logs
          image: diogojms/pcc_logs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://DriveCleaner:DriveCleanerG7@cluster0.bj3pzfe.mongodb.net/Logs"
            - name: SECRET
              value: "jfcnbjsnwdelwjcnewdlejbsfew"
            - name: LOGS_URI
              value: "guest:guest@localhost:5672/"
